# Change these first
owner: mahd-dev # Your GitHub organization or username, where this repository lives
repo: mahd-cloud-status # The name of this repository

sites:
  - name: Console
    url: https://console.mahd.cloud
  - name: Auth
    url: https://auth.mahd.cloud/debug/healthz
  - name: S3
    url: https://s3.mahd.cloud
    expectedStatusCodes:
      - 403
  - name: CDN
    url: https://cdn.mahd.cloud
    expectedStatusCodes:
      - 403
  - name: Mail
    url: https://admin.mahd.email
  - name: Webmail
    url: https://web.mahd.email
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mahd.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://mahd.cloud/assets/logo.svg
  theme: light
  themeUrl: https://status.mahd.cloud/mahd-theme.css
  favicon: https://mahd.cloud/favicon.svg
  faviconSvg: https://mahd.cloud/favicon.svg
  name: Status.Mahd.Cloud
  introTitle: "Real-Time Status of Mahd.Cloud services"
  introMessage: This is a status page which uses **real-time** data of our Mahd.Cloud services
  navbar:
    - title: Status
      href: /
    - title: Console
      href: https://console.mahd.cloud

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
